# Site settings
title: prehensile.github.io
email: me@prehensile.co.uk
description: "@prehensile's home on github"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://prehensile.github.io" # the base hostname & protocol for your site
twitter_username: prehensile
github_username: prehnsile

# Build settings
markdown: kramdown

exclude: ["*.sh", "package.json", "package-lock.json","Dockerfile","cv/src","cv/build"]